train:
  model: fasterrcnn_resnet50_fpn
  batch_size: 4
  epochs: 10
  lr: 0.000625
  weights_backbone: ResNet50_Weights.IMAGENET1K_V1

train_sparse:
  output_dir: data/train_sparse
  seed: 0
  dataset: data/coco_music_keypoints
  batch_size: 1
  lr: 0.01
  patience: 200
  epochs: 1000
  weights: true
  stride: 4
  dilation: 4
  label_whitelist:
  - gClef
  - fClef
  image_whitelist:
